-- Create orders table in ecommerce_order schema
-- Cross-schema FKs: users in ecommerce_identity, merchants in ecommerce_merchant
CREATE TABLE IF NOT EXISTS "orders" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT NOT NULL REFERENCES ecommerce_identity.users ("id") ON DELETE CASCADE,
    "merchant_id" BIGINT NOT NULL REFERENCES ecommerce_merchant.merchants ("id") ON DELETE CASCADE,
    "total_price" INT NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMP DEFAULT NULL
);

CREATE INDEX "idx_orders_user_id" ON "orders" ("user_id");
CREATE INDEX "idx_orders_merchant_id" ON "orders" ("merchant_id");
CREATE INDEX "idx_orders_total_price" ON "orders" ("total_price");
