-- Create order_items table in ecommerce_order schema
-- Cross-schema FK: products in ecommerce_catalog
CREATE TABLE IF NOT EXISTS "order_items" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "order_id" BIGINT NOT NULL REFERENCES "orders" ("id") ON DELETE CASCADE,
    "product_id" BIGINT NOT NULL REFERENCES ecommerce_catalog.products ("id") ON DELETE CASCADE,
    "quantity" INT NOT NULL,
    "price" INT NOT NULL,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMP DEFAULT NULL
);

CREATE INDEX "idx_order_items_order_id" ON "order_items" ("order_id");
