# Justfile for quarkus-grpc-ecommerce
# Wrapper recipes around the Maven multi-module build.
# Run `just` (no args) to list all recipes.
#
# Recipe names mirror the underlying `mvn ...` invocation so they read like
# the mvn commands they replace (e.g. `just mvn-test-all` ≡ `mvn test`).
# Short aliases (`test-all`, `compile`, `install`, `compile-common`) are also
# available for muscle-memory invocation.

# ─────────────────────────────────────────────────────────────────────────────
# Daily driver recipes — mirror the mvn commands the user requested.
# ─────────────────────────────────────────────────────────────────────────────

# Run tests for ALL modules (slow; requires prior `just mvn-install` because
# of reactor gRPC codegen dependencies — see README).
mvn-test-all:
    mvn test
alias test-all := mvn-test-all

# Compile all modules without running tests
mvn-compile:
    mvn compile
alias compile := mvn-compile

# Build artifacts + install every module into the local ~/.m2 repository.
# Run this once (or after major changes) before `just mvn-test-all` so that
# gRPC/DTO classes generated by Quarkus codegen in sibling modules are
# available on the classpath when reactor-mode tests compile.
mvn-install:
    mvn install -DskipTests
alias install := mvn-install

# Compile the `common` module and any of its Maven dependencies declared in
# this reactor (`-am` = "also make"). Useful when iterating on shared code
# without forcing a full build.
mvn-compile-common:
    mvn compile -pl common -am
alias compile-common := mvn-compile-common

# ─────────────────────────────────────────────────────────────────────────────
# Targeted recipes — fine-grained module operations for fast iteration.
# ─────────────────────────────────────────────────────────────────────────────

# Run tests for ONE module only, e.g. `just mvn-module-test gateway`.
# This is the fast/green path that always works because the module's
# inter-module JAR dependencies are pulled from the local ~/.m2 cache.
mvn-module-test module:
    mvn test -pl {{module}}
alias module-test := mvn-module-test

# Compile ONE module + its declared maven dependencies in this reactor.
mvn-module-build module:
    mvn compile -pl {{module}} -am
alias module-build := mvn-module-build

# Wipe every module's `target/` directory — nuclear option when stale codegen
# or class files are stuck. Pair with `just mvn-install` before re-running
# tests.
mvn-clean:
    mvn clean
alias clean := mvn-clean

# ─────────────────────────────────────────────────────────────────────────────
# Delivery & deployment recipes (Phase 6)
# Require: docker, kubectl, and optionally the ArgoCD CLI (`argocd`).
# ─────────────────────────────────────────────────────────────────────────────

# Build ONE service image with the k8s manifest name, e.g. `just docker-build auth`
# or `just docker-build gateway` (maps to ghcr.io/<owner>/quarkus-ecommerce/apigateway:latest).
# Owner defaults to mamangrust; override with GHCR_OWNER.
docker-build service:
    #!/usr/bin/env bash
    set -euo pipefail
    case "{{service}}" in
      gateway)   base=apigateway ;;  email-service) base=email ;; db-migration) base=migrate ;;
      *)         base={{service}} ;;
    esac
    docker build -f "{{service}}/Dockerfile" -t "ghcr.io/${GHCR_OWNER:-mamangrust}/quarkus-ecommerce/${base}:latest" .

# Build ALL service images (see build-docker-images.sh for the full mapping).
docker-build-all:
    ./build-docker-images.sh

# Render the full kustomize output for a base (or the whole platform) locally.
# e.g. `just kustomize-build auth` renders base/auth; `just kustomize-build all`
# renders every base (infra + services) into /tmp/k8s-rendered.
kustomize-build base:
    #!/usr/bin/env bash
    set -euo pipefail
    if [ "{{base}}" = "all" ]; then
      out=/tmp/k8s-rendered
      rm -rf "$out" && mkdir -p "$out"
      for d in deployments/kubernetes/base/*/; do
        kubectl kustomize "$d" > "$out/$(basename "$d").yaml"
      done
      echo "rendered $(ls "$out" | wc -l) bases -> $out"
    else
      kubectl kustomize "deployments/kubernetes/base/{{base}}"
    fi

# Dry-run apply a rendered base against the current cluster (requires a
# reachable kubeconfig). e.g. `just kustomize-dryrun auth`.
kustomize-dryrun base:
    kubectl kustomize "deployments/kubernetes/base/{{base}}" | kubectl apply --dry-run=client -f -

# Sync an ArgoCD application (or all apps) — GitOps rollout trigger.
# e.g. `just argocd-sync service-auth` or `just argocd-sync all`.
argocd-sync app:
    #!/usr/bin/env bash
    set -euo pipefail
    if [ "{{app}}" = "all" ]; then
      for a in deployments/gitops/argocd/apps/*.yaml; do
        argocd app sync "$(basename "$a" .yaml)"
      done
    else
      argocd app sync {{app}}
    fi

# Rollback an ArgoCD application to a previous revision, e.g.
# `just argocd-rollback service-order 2` (revision from `argocd app history`).
# This is the operational rollback test procedure for Phase 6.
argocd-rollback app revision:
    argocd app rollback {{app}} {{revision}}

# Full Phase 6 smoke: render every base, then dry-run them all.
# Fails fast on any kustomize/yaml error without touching the cluster.
deploy-smoke:
    #!/usr/bin/env bash
    set -euo pipefail
    for d in deployments/kubernetes/base/*/; do
      name=$(basename "$d")
      echo "== $name =="
      kubectl kustomize "$d" > /dev/null
    done
    echo "deploy-smoke: all bases render OK"

# ─────────────────────────────────────────────────────────────────────────────
# Load testing (Phase 7) — requires k6 and/or ghz installed locally.
# See load-test/README.md for the full procedure and Prometheus P95/P99
# queries.
# ─────────────────────────────────────────────────────────────────────────────

# Run the gateway HTTP load test (k6) against GATEWAY_URL.
load-test-gateway:
    k6 run load-test/gateway-smoke.js

# Run the gRPC load test against OrderQueryService (ghz).
load-test-grpc:
    ./load-test/grpc-order-query.sh

# Print the Prometheus queries used to extract p95/p99 from the histogram.
perf-queries:
    echo 'histogram_quantile(0.95, sum(rate(request_duration_seconds_bucket[5m])) by (le, method))'
    echo 'histogram_quantile(0.99, sum(rate(request_duration_seconds_bucket[5m])) by (le, method))'
