-- Create banners table
CREATE TABLE IF NOT EXISTS "banners" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(255) NOT NULL,
    "start_date" DATE NOT NULL,
    "end_date" DATE NOT NULL,
    "start_time" TIME NOT NULL,
    "end_time" TIME NOT NULL,
    "is_active" BOOLEAN DEFAULT TRUE,
    "created_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMP WITHOUT TIME ZONE NULL,
    CONSTRAINT "valid_date_range" CHECK (
        "end_date" IS NULL OR
        "start_date" IS NULL OR
        "end_date" >= "start_date"
    ),
    CONSTRAINT "valid_time_range" CHECK (
        "end_time" IS NULL OR
        "start_time" IS NULL OR
        "end_time" > "start_time"
    )
);

CREATE INDEX "idx_banners_active" ON "banners" ("is_active") WHERE "deleted_at" IS NULL;
CREATE INDEX "idx_banners_date_range" ON "banners" ("start_date", "end_date");
CREATE INDEX "idx_banners_time_range" ON "banners" ("start_time", "end_time");
CREATE INDEX "idx_banners_created_at" ON "banners" ("created_at");
CREATE INDEX "idx_banners_deleted_at" ON "banners" ("deleted_at") WHERE "deleted_at" IS NOT NULL;
