-- Create reset_tokens table for auth service
CREATE TABLE IF NOT EXISTS "reset_tokens" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" BIGINT NOT NULL,
    "token" VARCHAR(255) UNIQUE NOT NULL,
    "expiration" TIMESTAMP NOT NULL,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMP NULL
);

CREATE SEQUENCE IF NOT EXISTS reset_tokens_seq START 1 INCREMENT BY 50;

CREATE INDEX IF NOT EXISTS idx_reset_tokens_user_id ON "reset_tokens" ("user_id");
CREATE INDEX IF NOT EXISTS idx_reset_tokens_token ON "reset_tokens" ("token");
CREATE INDEX IF NOT EXISTS idx_reset_tokens_expiration ON "reset_tokens" ("expiration");
