-- Create categories table
CREATE TABLE IF NOT EXISTS "categories" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(100) NOT NULL,
    "description" TEXT,
    "slug_category" VARCHAR(100) UNIQUE,
    "image_category" TEXT,
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMP DEFAULT NULL
);

CREATE INDEX "idx_categories_slug" ON "categories" ("slug_category");
CREATE INDEX "idx_categories_created_at" ON "categories" ("created_at");
