#!/usr/bin/env python3
"""Generate the local gateway Hurl E2E suite (full CRUD + read + stats).

The generated file is one sequential Hurl file so captured JWTs and entity IDs
can be reused. The mutation section creates marker-prefixed entities through
the real gateway (valid business payloads), exercises soft-delete/restore, and
is followed by the stats section so the statistics see real data. Permanent
/all-delete routes are probed with the user token and must be denied (403).
"""
from pathlib import Path

OUT = Path(__file__).with_name("e2e") / "gateway-all-endpoints.hurl"


def get(path: str, token: str = "user_token") -> list[str]:
    query = "" if "?" in path else "?page=1&size=20&search="
    return ["", f"GET {{{{base_url}}}}{path}{query}", f"Authorization: Bearer {{{{{token}}}}}", "HTTP 200"]


def post(path: str, body: str, token: str = "user_token", status: str = "201",
         captures: list[str] | None = None, extra_asserts: list[str] | None = None) -> list[str]:
    block = ["", f"POST {{{{base_url}}}}{path}", f"Authorization: Bearer {{{{{token}}}}}",
             "Content-Type: application/json", "", body, f"HTTP {status}"]
    if captures:
        block += ["[Captures]"] + captures
    if extra_asserts:
        block += ["[Asserts]"] + extra_asserts
    return block


def put(path: str, body: str, token: str = "user_token", status: str = "200") -> list[str]:
    return ["", f"PUT {{{{base_url}}}}{path}", f"Authorization: Bearer {{{{{token}}}}}",
            "Content-Type: application/json", "", body, f"HTTP {status}"]


def delete(path: str, token: str = "admin_token", status: str = "200") -> list[str]:
    return ["", f"DELETE {{{{base_url}}}}{path}", f"Authorization: Bearer {{{{{token}}}}}", f"HTTP {status}"]


lines = [
    "# Generated by load-test/generate-hurl-e2e.py",
    "# Run through load-test/run-hurl-e2e.sh; do not run this file with missing variables.",
    "",
    "GET {{base_url}}/q/health/ready",
    "HTTP 200",
    "[Asserts]",
    'jsonpath "$.status" == "UP"',
    "",
    "POST {{base_url}}/api/auth/login",
    "Content-Type: application/json",
    "",
    '{"email":"{{email}}","password":"{{password}}"}',
    "HTTP 200",
    "[Captures]",
    'user_token: jsonpath "$.data.accessToken"',
    'refresh_token: jsonpath "$.data.refreshToken"',
    "[Asserts]",
    'jsonpath "$.status" == "success"',
    'jsonpath "$.data.accessToken" exists',
    "",
    "GET {{base_url}}/api/auth/me?userId={{user_id}}",
    "Authorization: Bearer {{user_token}}",
    "HTTP 200",
    "[Asserts]",
    'jsonpath "$.data.id" == {{user_id}}',
    "",
    "POST {{base_url}}/api/auth/refresh",
    "Content-Type: application/json",
    "",
    '{"refreshToken":"{{refresh_token}}"}',
    "HTTP 200",
    "[Asserts]",
    'jsonpath "$.status" == "success"',
    "",
    "# ---- Auth: full register flow (gateway -> auth -> user create -> role resolve) ----",
    "# Register is intentionally covered: it exercises the whole internal gRPC chain",
    "# (auth calls user service create, which resolves roles via the role service).",
    "POST {{base_url}}/api/auth/register",
    "Content-Type: application/json",
    "",
    '{"firstname":"Hurl","lastname":"E2E","email":"{{marker_lower}}@example.test","password":"HurlE2EPass!2026"}',
    "HTTP 201",
    "[Asserts]",
    'jsonpath "$.status" == "success"',
    "",
    "# Round-trip: the newly registered user must be able to log in.",
    "POST {{base_url}}/api/auth/login",
    "Content-Type: application/json",
    "",
    '{"email":"{{marker_lower}}@example.test","password":"HurlE2EPass!2026"}',
    "HTTP 200",
    "[Asserts]",
    'jsonpath "$.status" == "success"',
    'jsonpath "$.data.accessToken" exists',
]

# ---- Section 1: read-only GET coverage (fixture IDs from vars.properties) ----
get_routes = [
    ("/api/banners", "user"), ("/api/banners/active", "user"), ("/api/banners/trashed", "admin"), ("/api/banners/{{fixture_banner_id}}", "user"),
    ("/api/carts/user/{{user_id}}", "user"),
    ("/api/category", "user"), ("/api/category/active", "user"), ("/api/category/trashed", "admin"), ("/api/category/{{fixture_category_id}}", "user"),
    ("/api/merchant-awards", "user"), ("/api/merchant-awards/active", "user"), ("/api/merchant-awards/trashed", "admin"), ("/api/merchant-awards/{{fixture_award_id}}", "user"),
    ("/api/merchant-businesses", "user"), ("/api/merchant-businesses/active", "user"), ("/api/merchant-businesses/trashed", "admin"), ("/api/merchant-businesses/{{fixture_business_id}}", "user"),
    ("/api/merchant-details", "user"), ("/api/merchant-details/active", "user"), ("/api/merchant-details/trashed", "admin"), ("/api/merchant-details/{{fixture_detail_id}}", "user"),
    ("/api/merchant-documents", "user"), ("/api/merchant-documents/active", "user"), ("/api/merchant-documents/trashed", "admin"), ("/api/merchant-documents/{{fixture_document_id}}", "user"),
    ("/api/merchant-policies", "user"), ("/api/merchant-policies/active", "user"), ("/api/merchant-policies/trashed", "admin"), ("/api/merchant-policies/{{fixture_policy_id}}", "user"),
    ("/api/merchants", "user"), ("/api/merchants/active", "user"), ("/api/merchants/trashed", "admin"), ("/api/merchants/{{fixture_merchant_id}}", "user"),
    ("/api/orders", "user"), ("/api/orders/active", "user"), ("/api/orders/trashed", "admin"), ("/api/orders/{{fixture_order_id}}", "user"),
    ("/api/products", "user"), ("/api/products/active", "user"), ("/api/products/trashed", "admin"), ("/api/products/{{fixture_product_id}}", "user"),
    ("/api/review-details", "user"), ("/api/review-details/active", "user"), ("/api/review-details/trashed", "admin"), ("/api/review-details/{{fixture_review_detail_id}}", "user"),
    ("/api/reviews", "user"), ("/api/reviews/product/{{product_id}}", "user"), ("/api/reviews/merchant/{{merchant_id}}", "user"), ("/api/reviews/active", "user"), ("/api/reviews/trashed", "admin"), ("/api/reviews/{{fixture_review_id}}", "user"),
    ("/api/roles", "admin"), ("/api/roles/{{role_id}}", "admin"), ("/api/roles/name/ROLE_USER", "admin"), ("/api/roles/active", "admin"), ("/api/roles/trashed", "admin"), ("/api/roles/user/{{user_id}}", "admin"),
    ("/api/shipping-addresses", "user"), ("/api/shipping-addresses/order/{{order_id}}", "user"), ("/api/shipping-addresses/active", "user"), ("/api/shipping-addresses/trashed", "admin"), ("/api/shipping-addresses/{{fixture_shipping_id}}", "user"),
    ("/api/sliders", "user"), ("/api/sliders/active", "user"), ("/api/sliders/trashed", "admin"), ("/api/sliders/{{fixture_slider_id}}", "user"),
    ("/api/transactions", "user"), ("/api/transactions/merchant/{{merchant_id}}", "user"), ("/api/transactions/{{fixture_transaction_id}}", "user"), ("/api/transactions/active", "user"), ("/api/transactions/trashed", "admin"),
    ("/api/users", "admin"), ("/api/users/active", "admin"), ("/api/users/trashed", "admin"), ("/api/users/{{fixture_user_id}}", "user"),
]
for path, role in get_routes:
    lines += get(path, role + "_token")

lines += ["", "# ================= FULL CRUD ================="]

# ---- Category ----
lines += post("/api/category/create",
              '{"name":"{{marker}}_Category","description":"Hurl E2E category","slugCategory":"{{marker_lower}}-category","imageCategory":"test/hurl-category.png"}',
              token="admin_token",
              captures=['category_id: jsonpath "$.data.id"'])
lines += get("/api/category/{{category_id}}")
lines += post("/api/category/update/{{category_id}}",
              '{"name":"{{marker}}_Category_Updated","description":"Hurl updated","slugCategory":"{{marker_lower}}-category-updated","imageCategory":"test/hurl-category-2.png"}',
              token="admin_token", status="200")
lines += post("/api/category/trashed/{{category_id}}", "{}", token="admin_token", status="200")
lines += post("/api/category/restore/{{category_id}}", "{}", token="admin_token", status="200")

# ---- Merchant ----
lines += post("/api/merchants",
              '{"userId":{{user_id}},"name":"{{marker}}_Merchant","description":"Hurl E2E merchant","address":"Test Street 1","contactEmail":"{{email}}","contactPhone":"081234567890","status":"PENDING"}',
              token="user_token",
              captures=['merchant_id: jsonpath "$.data.id"'])
lines += get("/api/merchants/{{merchant_id}}")
lines += put("/api/merchants/{{merchant_id}}",
             '{"userId":{{user_id}},"name":"{{marker}}_Merchant_Updated","description":"Updated","address":"Test Street 2","contactEmail":"{{email}}","contactPhone":"081234567891","status":"SUCCESS"}')
lines += delete("/api/merchants/{{merchant_id}}")
lines += post("/api/merchants/restore/{{merchant_id}}", "{}", token="admin_token", status="200")

# ---- Merchant Detail ----
lines += post("/api/merchant-details/create",
              '{"merchantId":{{merchant_id}},"displayName":"{{marker}} Detail","coverImageUrl":"https://example.test/cover.png","logoUrl":"https://example.test/logo.png","shortDescription":"Detail","websiteUrl":"https://example.test"}',
              token="admin_token",
              captures=['merchant_detail_id: jsonpath "$.data.id"'])
lines += get("/api/merchant-details/{{merchant_detail_id}}")
lines += post("/api/merchant-details/update/{{merchant_detail_id}}",
              '{"displayName":"{{marker}} Detail Updated","coverImageUrl":"https://example.test/cover2.png","logoUrl":"https://example.test/logo2.png","shortDescription":"Updated","websiteUrl":"https://example.test/updated"}',
              token="admin_token", status="200")
lines += delete("/api/merchant-details/{{merchant_detail_id}}")
lines += post("/api/merchant-details/restore/{{merchant_detail_id}}", "{}", token="admin_token", status="200")

# ---- Merchant Business ----
lines += post("/api/merchant-businesses/create",
              '{"merchantId":{{merchant_id}},"businessType":"RETAIL","taxId":"{{marker}}TAX","establishedYear":2020,"numberOfEmployees":5,"websiteUrl":"https://example.test"}',
              token="admin_token",
              captures=['merchant_business_id: jsonpath "$.data.id"'])
lines += get("/api/merchant-businesses/{{merchant_business_id}}")
lines += post("/api/merchant-businesses/update/{{merchant_business_id}}",
              '{"businessType":"WHOLESALE","taxId":"{{marker}}TAX2","establishedYear":2021,"numberOfEmployees":7,"websiteUrl":"https://example.test/updated"}',
              token="admin_token", status="200")
lines += delete("/api/merchant-businesses/{{merchant_business_id}}")
lines += post("/api/merchant-businesses/restore/{{merchant_business_id}}", "{}", token="admin_token", status="200")

# ---- Merchant Policy ----
lines += post("/api/merchant-policies/create",
              '{"merchantId":{{merchant_id}},"policyType":"RETURN","title":"{{marker}} Policy","description":"Return policy"}',
              token="admin_token",
              captures=['merchant_policy_id: jsonpath "$.data.id"'])
lines += get("/api/merchant-policies/{{merchant_policy_id}}")
lines += post("/api/merchant-policies/update/{{merchant_policy_id}}",
              '{"policyType":"RETURN","title":"{{marker}} Policy Updated","description":"Updated policy"}',
              token="admin_token", status="200")
lines += delete("/api/merchant-policies/{{merchant_policy_id}}")
lines += post("/api/merchant-policies/restore/{{merchant_policy_id}}", "{}", token="admin_token", status="200")

# ---- Merchant Award ----
lines += post("/api/merchant-awards/create",
              '{"merchantId":{{merchant_id}},"title":"{{marker}} Award","description":"Award","issuedBy":"Freebuff","issueDate":"2026-01-01","expiryDate":"2027-01-01","certificateUrl":"https://example.test/cert.pdf"}',
              token="admin_token",
              captures=['merchant_award_id: jsonpath "$.data.id"'])
lines += get("/api/merchant-awards/{{merchant_award_id}}")
lines += post("/api/merchant-awards/update/{{merchant_award_id}}",
              '{"title":"{{marker}} Award Updated","description":"Updated","issuedBy":"Freebuff","issueDate":"2026-01-01","expiryDate":"2027-01-01","certificateUrl":"https://example.test/cert2.pdf"}',
              token="admin_token", status="200")
lines += delete("/api/merchant-awards/{{merchant_award_id}}")
lines += post("/api/merchant-awards/restore/{{merchant_award_id}}", "{}", token="admin_token", status="200")

# ---- Merchant Document ----
lines += post("/api/merchant-documents",
              '{"merchantId":{{merchant_id}},"documentType":"KTP","documentUrl":"https://example.test/docs/ktp.pdf"}',
              token="admin_token",
              captures=['merchant_document_id: jsonpath "$.data.documentId"'])
lines += get("/api/merchant-documents/{{merchant_document_id}}")
lines += put("/api/merchant-documents/{{merchant_document_id}}",
             '{"documentId":{{merchant_document_id}},"merchantId":{{merchant_id}},"documentType":"NPWP","documentUrl":"https://example.test/docs/npwp.pdf"}',
             token="admin_token")
lines += post("/api/merchant-documents/trash/{{merchant_document_id}}", "{}", token="admin_token", status="200")
lines += post("/api/merchant-documents/restore/{{merchant_document_id}}", "{}", token="admin_token", status="200")

# ---- Product ----
lines += post("/api/products/create",
              '{"merchantId":{{merchant_id}},"categoryId":{{category_id}},"name":"{{marker}}_Product","description":"Full CRUD product","price":12500,"countInStock":20,"brand":"Freebuff","weight":500,"rating":5,"slugProduct":"{{marker_lower}}-product","imageProduct":"test/product.png","barcode":"BC{{marker}}"}',
              token="user_token",
              captures=['product_id: jsonpath "$.data.id"'])
lines += get("/api/products/{{product_id}}")
lines += post("/api/products/update/{{product_id}}",
              '{"merchantId":{{merchant_id}},"categoryId":{{category_id}},"name":"{{marker}}_Product_Updated","description":"Updated","price":13000,"countInStock":18,"brand":"Freebuff","weight":550,"rating":5,"slugProduct":"{{marker_lower}}-product-updated","imageProduct":"test/product-2.png","barcode":"BCU{{marker}}"}',
              token="user_token", status="200")

# ---- Cart ----
lines += post("/api/carts",
              '{"quantity":2,"productId":{{product_id}},"userId":{{user_id}}}',
              token="user_token",
              captures=['cart_id: jsonpath "$.data.id"'])
lines += get("/api/carts/user/{{user_id}}")
lines += delete("/api/carts/{{cart_id}}/user/{{user_id}}", token="user_token")

# ---- Order ----
lines += post("/api/orders/create",
              '{"merchantId":{{merchant_id}},"userId":{{user_id}},"totalPrice":26000,"items":[{"productId":{{product_id}},"quantity":2,"price":13000}],"shipping":{"alamat":"Test Address","provinsi":"DKI Jakarta","kota":"Jakarta","courier":"JNE","shippingMethod":"REG","shippingCost":10000,"negara":"Indonesia"}}',
              token="user_token",
              captures=['order_id: jsonpath "$.data.id"'])
lines += get("/api/orders/{{order_id}}")

# ---- Shipping Address (before order update, which needs shippingId) ----
lines += post("/api/shipping-addresses/create",
              '{"orderId":{{order_id}},"alamat":"Updated Address","provinsi":"Jawa Barat","kota":"Bandung","courier":"JNE","shippingMethod":"YES","shippingCost":15000,"negara":"Indonesia"}',
              token="user_token",
              captures=['shipping_id: jsonpath "$.data.id"'])
lines += get("/api/shipping-addresses/{{shipping_id}}")
lines += post("/api/shipping-addresses/update/{{shipping_id}}",
              '{"orderId":{{order_id}},"alamat":"Updated Address 2","provinsi":"Jawa Barat","kota":"Bandung","courier":"JNE","shippingMethod":"REG","shippingCost":12000,"negara":"Indonesia"}',
              token="user_token", status="200")

# ---- Order update (shippingAddress required; items empty keeps it valid) ----
lines += post("/api/orders/update/{{order_id}}",
              '{"userId":{{user_id}},"totalPrice":26000,"items":[],"shipping":{"shippingId":{{shipping_id}},"orderId":{{order_id}},"alamat":"Updated Address 2","provinsi":"Jawa Barat","kota":"Bandung","courier":"JNE","shippingMethod":"REG","shippingCost":12000,"negara":"Indonesia"}}',
              token="user_token", status="200")

# ---- Transaction ----
lines += post("/api/transactions/create",
              '{"orderId":{{order_id}},"merchantId":{{merchant_id}},"paymentMethod":"BANK_TRANSFER","amount":40000,"userId":{{user_id}},"paymentStatus":"PENDING"}',
              token="user_token",
              captures=['transaction_id: jsonpath "$.data.id"'])
lines += get("/api/transactions/{{transaction_id}}")
lines += get("/api/transactions/order/{{order_id}}")
lines += post("/api/transactions/update/{{transaction_id}}",
              '{"orderId":{{order_id}},"merchantId":{{merchant_id}},"paymentMethod":"BANK_TRANSFER","amount":40000,"paymentStatus":"SUCCESS"}',
              token="user_token", status="200")

# ---- Review ----
lines += post("/api/reviews/create",
              '{"userId":{{user_id}},"productId":{{product_id}},"name":"{{marker}} Review","comment":"Excellent test product","rating":5}',
              token="user_token",
              captures=['review_id: jsonpath "$.data.id"'])
lines += get("/api/reviews/{{review_id}}")
lines += post("/api/reviews/update/{{review_id}}",
              '{"name":"{{marker}} Review Updated","comment":"Updated review","rating":4}',
              token="user_token", status="200")

# ---- Review Detail ----
lines += post("/api/review-details/create",
              '{"reviewId":{{review_id}},"type":"photo","url":"https://example.test/review.png","caption":"Test photo"}',
              token="user_token",
              captures=['review_detail_id: jsonpath "$.data.id"'])
lines += get("/api/review-details/{{review_detail_id}}")
lines += post("/api/review-details/update/{{review_detail_id}}",
              '{"type":"photo","url":"https://example.test/review-2.png","caption":"Updated photo"}',
              token="user_token", status="200")
lines += delete("/api/review-details/{{review_detail_id}}")
lines += post("/api/review-details/restore/{{review_detail_id}}", "{}", token="admin_token", status="200")

# ---- Slider ----
lines += post("/api/sliders/create",
              '{"name":"{{marker}}_Slider","image":"test/hurl-slider.png"}',
              token="admin_token",
              captures=['slider_id: jsonpath "$.data.id"'])
lines += post("/api/sliders/update/{{slider_id}}",
              '{"name":"{{marker}}_Slider_Updated","image":"test/hurl-slider-2.png"}',
              token="admin_token", status="200")
lines += delete("/api/sliders/{{slider_id}}")
lines += post("/api/sliders/restore/{{slider_id}}", "{}", token="admin_token", status="200")

# ---- Banner ----
lines += post("/api/banners",
              '{"name":"{{marker}}_Banner","startDate":"2026-01-01","endDate":"2026-12-31","startTime":"09:00:00","endTime":"18:00:00","isActive":true}',
              token="admin_token",
              captures=['banner_id: jsonpath "$.data.bannerId"'])
lines += get("/api/banners/{{banner_id}}")
lines += put("/api/banners/{{banner_id}}",
             '{"name":"{{marker}}_Banner_Updated","startDate":"2026-01-01","endDate":"2026-12-31","startTime":"10:00:00","endTime":"19:00:00","isActive":true}',
             token="admin_token")
lines += delete("/api/banners/{{banner_id}}")
lines += post("/api/banners/restore/{{banner_id}}", "{}", token="admin_token", status="200")

# ---- Role ----
lines += post("/api/roles",
              '{"name":"{{marker}}_ROLE"}',
              token="admin_token",
              captures=['role_id: jsonpath "$.data.id"'])
lines += get("/api/roles/{{role_id}}", token="admin_token")
lines += put("/api/roles/{{role_id}}",
             '{"name":"{{marker}}_ROLE_UPDATED"}',
             token="admin_token")
lines += delete("/api/roles/{{role_id}}")
lines += post("/api/roles/restore/{{role_id}}", "{}", token="admin_token", status="200")

# ---- User (self update) ----
lines += get("/api/users/{{user_id}}")
lines += put("/api/users/{{user_id}}",
             '{"firstname":"Freebuff","lastname":"FullTestUpdated","email":"{{email}}","password":"{{password}}","confirmPassword":"{{password}}"}',
             token="user_token")

# ---- Stats (after mutations so real data is present; current period = 2026-08) ----
lines += ["", "# ================= STATS ================="]
stats = [
    "/api/category/monthly-total-pricing?year=2026&month=1", "/api/category/yearly-total-pricing?year=2026",
    "/api/category/merchant/monthly-total-pricing?merchantId={{merchant_id}}&year=2026&month=8", "/api/category/merchant/yearly-total-pricing?merchantId={{merchant_id}}&year=2026",
    "/api/category/mycategory/monthly-total-pricing?categoryId={{category_id}}&year=2026&month=8", "/api/category/mycategory/yearly-total-pricing?categoryId={{category_id}}&year=2026",
    "/api/category/monthly-pricing?year=2026", "/api/category/yearly-pricing?year=2026",
    "/api/category/merchant/monthly-pricing?merchantId={{merchant_id}}&year=2026", "/api/category/merchant/yearly-pricing?merchantId={{merchant_id}}&year=2026",
    "/api/category/mycategory/monthly-pricing?categoryId={{category_id}}&year=2026", "/api/category/mycategory/yearly-pricing?categoryId={{category_id}}&year=2026",
    "/api/orders/stats/monthly-revenue?year=2026&month=1", "/api/orders/stats/yearly-revenue?year=2026",
    "/api/orders/stats/monthly-total-revenue?year=2026&month=8", "/api/orders/stats/yearly-total-revenue?year=2026",
    "/api/orders/stats/merchant/{{merchant_id}}/monthly-revenue?year=2026&month=8", "/api/orders/stats/merchant/{{merchant_id}}/yearly-revenue?year=2026",
    "/api/orders/stats/merchant/{{merchant_id}}/monthly-total-revenue?year=2026&month=8", "/api/orders/stats/merchant/{{merchant_id}}/yearly-total-revenue?year=2026",
    "/api/transactions/stats/monthly-amount-success?year=2026&month=8", "/api/transactions/stats/yearly-amount-success?year=2026",
    "/api/transactions/stats/monthly-amount-failed?year=2026&month=8", "/api/transactions/stats/yearly-amount-failed?year=2026",
    "/api/transactions/stats/monthly-method-success?year=2026&month=8", "/api/transactions/stats/yearly-method-success?year=2026",
    "/api/transactions/stats/monthly-method-failed?year=2026&month=8", "/api/transactions/stats/yearly-method-failed?year=2026",
    "/api/transactions/stats/merchant/{{merchant_id}}/monthly-amount-success?year=2026&month=8", "/api/transactions/stats/merchant/{{merchant_id}}/yearly-amount-success?year=2026",
    "/api/transactions/stats/merchant/{{merchant_id}}/monthly-amount-failed?year=2026&month=8", "/api/transactions/stats/merchant/{{merchant_id}}/yearly-amount-failed?year=2026",
    "/api/transactions/stats/merchant/{{merchant_id}}/monthly-method-success?year=2026&month=8", "/api/transactions/stats/merchant/{{merchant_id}}/yearly-method-success?year=2026",
    "/api/transactions/stats/merchant/{{merchant_id}}/monthly-method-failed?year=2026&month=8", "/api/transactions/stats/merchant/{{merchant_id}}/yearly-method-failed?year=2026",
]
for path in stats:
    lines += get(path, token="admin_token")

# ---- Safety probes: permanent/all must be denied for the user token ----
safety = [
    ("DELETE", "/api/banners/permanent/{{banner_id}}"), ("POST", "/api/banners/permanent/all"), ("POST", "/api/banners/restore/all"),
    ("DELETE", "/api/category/permanent/{{category_id}}"), ("POST", "/api/category/permanent/all"), ("POST", "/api/category/restore/all"),
    ("DELETE", "/api/products/permanent/{{product_id}}"), ("POST", "/api/products/permanent/all"), ("POST", "/api/products/restore/all"),
    ("DELETE", "/api/roles/permanent/{{role_id}}"), ("POST", "/api/roles/permanent/all"), ("POST", "/api/roles/restore/all"),
    ("DELETE", "/api/users/permanent/{{user_id}}"), ("POST", "/api/users/permanent/all"), ("POST", "/api/users/restore/all"),
]
for method, path in safety:
    lines += ["", f"{method} {{{{base_url}}}}{path}", "Authorization: Bearer {{user_token}}", "HTTP 403"]

# ---- Invalid-ID contract: id=0 must be rejected with HTTP 400 ----
# Locks the Fase 2 guard contract: every ID-consuming gRPC handler guards
# id <= 0 (IdValidator) and the gateway maps gRPC INVALID_ARGUMENT -> 400
# (GrpcExceptionMapper). Asserts both the HTTP status and the error body.
lines += ["", "# ================= INVALID-ID CONTRACT (id=0 -> 400) ================="]


def invalid_id(method: str, path: str, token: str, body: str | None = None) -> list[str]:
    block = ["", f"{method} {{{{base_url}}}}{path}", f"Authorization: Bearer {{{{{token}}}}}"]
    if body is not None:
        block += ["Content-Type: application/json", "", body]
    block += ["HTTP 400", "[Asserts]", 'jsonpath "$.status" == "error"',
              'jsonpath "$.message" contains "positive integer"']
    return block


# A. Query by id=0: every primary-id GET route (and sub-resource ID lookups).
invalid_get_routes = [
    ("/api/banners/0", "user_token"),
    ("/api/category/0", "user_token"),
    ("/api/merchant-awards/0", "user_token"),
    ("/api/merchant-businesses/0", "user_token"),
    ("/api/merchant-details/0", "user_token"),
    ("/api/merchant-documents/0", "user_token"),
    ("/api/merchant-policies/0", "user_token"),
    ("/api/merchants/0", "user_token"),
    ("/api/orders/0", "user_token"),
    ("/api/products/0", "user_token"),
    ("/api/review-details/0", "user_token"),
    ("/api/reviews/0", "user_token"),
    ("/api/roles/0", "admin_token"),
    ("/api/shipping-addresses/0", "user_token"),
    ("/api/sliders/0", "user_token"),
    ("/api/transactions/0", "user_token"),
    ("/api/users/0", "user_token"),
    # sub-resource ID lookups
    ("/api/carts/user/0", "user_token"),
    ("/api/reviews/product/0", "user_token"),
    ("/api/reviews/merchant/0", "user_token"),
    ("/api/roles/user/0", "admin_token"),
    ("/api/shipping-addresses/order/0", "user_token"),
    ("/api/transactions/merchant/0", "user_token"),
    ("/api/transactions/order/0", "user_token"),
]
for path, tok in invalid_get_routes:
    lines += invalid_id("GET", path, tok)

# B. Mutations with id=0 in the path (valid JSON body; the handler guard fires first).
invalid_mutations = [
    ("POST", "/api/category/update/0", "admin_token", '{"name":"x","description":"x","slugCategory":"x","imageCategory":"x"}'),
    ("POST", "/api/category/trashed/0", "admin_token", "{}"),
    ("POST", "/api/category/restore/0", "admin_token", "{}"),
    ("PUT", "/api/merchants/0", "user_token", '{"name":"x","status":"PENDING"}'),
    ("DELETE", "/api/merchants/0", "admin_token", None),
    ("POST", "/api/merchants/restore/0", "admin_token", "{}"),
    ("POST", "/api/merchant-details/update/0", "admin_token", '{"displayName":"x"}'),
    ("DELETE", "/api/merchant-details/0", "admin_token", None),
    ("POST", "/api/merchant-details/restore/0", "admin_token", "{}"),
    ("POST", "/api/merchant-businesses/update/0", "admin_token", '{"businessType":"RETAIL"}'),
    ("DELETE", "/api/merchant-businesses/0", "admin_token", None),
    ("POST", "/api/merchant-businesses/restore/0", "admin_token", "{}"),
    ("POST", "/api/merchant-policies/update/0", "admin_token", '{"policyType":"RETURN"}'),
    ("DELETE", "/api/merchant-policies/0", "admin_token", None),
    ("POST", "/api/merchant-policies/restore/0", "admin_token", "{}"),
    ("POST", "/api/merchant-awards/update/0", "admin_token", '{"title":"x"}'),
    ("DELETE", "/api/merchant-awards/0", "admin_token", None),
    ("POST", "/api/merchant-awards/restore/0", "admin_token", "{}"),
    ("PUT", "/api/merchant-documents/0", "admin_token", '{"documentType":"KTP"}'),
    ("POST", "/api/merchant-documents/trash/0", "admin_token", "{}"),
    ("POST", "/api/merchant-documents/restore/0", "admin_token", "{}"),
    ("POST", "/api/products/update/0", "user_token", '{"name":"x","price":1}'),
    ("DELETE", "/api/carts/0/user/{{user_id}}", "user_token", None),
    ("POST", "/api/orders/update/0", "user_token", '{"totalPrice":1,"items":[]}'),
    ("POST", "/api/shipping-addresses/update/0", "user_token", '{"alamat":"x"}'),
    ("POST", "/api/transactions/update/0", "user_token", '{"amount":1,"paymentStatus":"SUCCESS"}'),
    ("POST", "/api/reviews/update/0", "user_token", '{"rating":5}'),
    ("POST", "/api/review-details/update/0", "user_token", '{"type":"photo"}'),
    ("DELETE", "/api/review-details/0", "admin_token", None),
    ("POST", "/api/review-details/restore/0", "admin_token", "{}"),
    ("POST", "/api/sliders/update/0", "admin_token", '{"name":"x"}'),
    ("DELETE", "/api/sliders/0", "admin_token", None),
    ("POST", "/api/sliders/restore/0", "admin_token", "{}"),
    ("PUT", "/api/banners/0", "admin_token", '{"name":"x"}'),
    ("DELETE", "/api/banners/0", "admin_token", None),
    ("POST", "/api/banners/restore/0", "admin_token", "{}"),
    ("PUT", "/api/roles/0", "admin_token", '{"name":"x"}'),
    ("DELETE", "/api/roles/0", "admin_token", None),
    ("POST", "/api/roles/restore/0", "admin_token", "{}"),
    ("PUT", "/api/users/0", "user_token", '{"firstname":"A","lastname":"B","email":"x@example.test","password":"Pass!234567","confirmPassword":"Pass!234567"}'),
]
for method, path, tok, body in invalid_mutations:
    lines += invalid_id(method, path, tok, body)

# C. Body-level guards: required IDs inside create/update payloads must be 400.
invalid_bodies = [
    ("POST", "/api/products/create", "user_token",
     '{"merchantId":0,"categoryId":{{category_id}},"name":"X","description":"x","price":100,"countInStock":5,"brand":"F","weight":100,"rating":5,"slugProduct":"x","imageProduct":"x","barcode":"X"}'),
    ("POST", "/api/products/create", "user_token",
     '{"merchantId":{{merchant_id}},"categoryId":0,"name":"X","description":"x","price":100,"countInStock":5,"brand":"F","weight":100,"rating":5,"slugProduct":"x","imageProduct":"x","barcode":"X"}'),
    ("POST", "/api/orders/create", "user_token",
     '{"merchantId":{{merchant_id}},"userId":{{user_id}},"totalPrice":100,"items":[{"productId":0,"quantity":1,"price":100}],"shipping":{"alamat":"A","provinsi":"P","kota":"K","courier":"JNE","shippingMethod":"REG","shippingCost":1000,"negara":"ID"}}'),
    ("POST", "/api/orders/update/{{order_id}}", "user_token",
     '{"userId":{{user_id}},"totalPrice":100,"items":[],"shipping":{"shippingId":0,"orderId":{{order_id}},"alamat":"A","provinsi":"P","kota":"K","courier":"JNE","shippingMethod":"REG","shippingCost":1000,"negara":"ID"}}'),
    ("POST", "/api/merchant-details/create", "admin_token",
     '{"merchantId":0,"displayName":"X","coverImageUrl":"https://x.test/a.png","logoUrl":"https://x.test/l.png","shortDescription":"x","websiteUrl":"https://x.test"}'),
]
for method, path, tok, body in invalid_bodies:
    lines += invalid_id(method, path, tok, body)

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(OUT)
