-- Create merchant_business_information table
CREATE TABLE IF NOT EXISTS "merchant_business_information" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "merchant_id" BIGINT NOT NULL REFERENCES "merchants" ("id") ON DELETE CASCADE,
    "business_type" VARCHAR(100),
    "tax_id" VARCHAR(50),
    "established_year" INT,
    "number_of_employees" INT,
    "website_url" VARCHAR(255),
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMP DEFAULT NULL
);

CREATE INDEX "idx_merchant_business_info_merchant_id" ON "merchant_business_information" ("merchant_id");
