-- Create merchant_certifications_and_awards table
CREATE TABLE IF NOT EXISTS "merchant_certifications_and_awards" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "merchant_id" BIGINT NOT NULL REFERENCES "merchants" ("id") ON DELETE CASCADE,
    "title" VARCHAR(255) NOT NULL,
    "description" TEXT,
    "issued_by" VARCHAR(255),
    "issue_date" DATE,
    "expiry_date" DATE,
    "certificate_url" VARCHAR(255),
    "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMP DEFAULT NULL
);

CREATE INDEX "idx_certifications_merchant_id" ON "merchant_certifications_and_awards" ("merchant_id");
CREATE INDEX "idx_certifications_issue_date" ON "merchant_certifications_and_awards" ("issue_date");
